[project]
name = "lizarslair"
version = "0.1.0"
classifiers = ["Private :: Do Not Upload"]
requires-python = ">=3.13"
dependencies = [
  "pygame>=2.6.1",
]

[dependency-groups]
dev = [
  "pyinstaller>=6.14.2",
  "pyinstaller-hooks-contrib>=2025.8",
  "pytest>=8.4.1",
  "ruff>=0.12.7",
]
